# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\일희\Desktop\Consult2\GUI\template3.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Consult2(object):
    def setupUi(self, Consult2):
        Consult2.setObjectName("Consult2")
        Consult2.resize(1058, 616)
        self.centralwidget = QtWidgets.QWidget(Consult2)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Consult = QtWidgets.QGroupBox(self.tab_1)
        self.Consult.setObjectName("Consult")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Consult)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.consult_folderBtn = QtWidgets.QPushButton(self.Consult)
        self.consult_folderBtn.setObjectName("consult_folderBtn")
        self.gridLayout_3.addWidget(self.consult_folderBtn, 6, 0, 1, 2)
        self.end_m = QtWidgets.QDateEdit(self.Consult)
        self.end_m.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.end_m.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.end_m.setMinimumDate(QtCore.QDate(2010, 1, 1))
        self.end_m.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.end_m.setCurrentSectionIndex(1)
        self.end_m.setDate(QtCore.QDate(2020, 1, 1))
        self.end_m.setObjectName("end_m")
        self.gridLayout_3.addWidget(self.end_m, 1, 1, 1, 1)
        self.year_checkBX_1 = QtWidgets.QCheckBox(self.Consult)
        self.year_checkBX_1.setObjectName("year_checkBX_1")
        self.gridLayout_3.addWidget(self.year_checkBX_1, 0, 0, 1, 1)
        self.email_Btn = QtWidgets.QPushButton(self.Consult)
        self.email_Btn.setObjectName("email_Btn")
        self.gridLayout_3.addWidget(self.email_Btn, 5, 0, 1, 2)
        self.file_Btn = QtWidgets.QPushButton(self.Consult)
        self.file_Btn.setObjectName("file_Btn")
        self.gridLayout_3.addWidget(self.file_Btn, 7, 0, 1, 2)
        self.start_m = QtWidgets.QDateEdit(self.Consult)
        self.start_m.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.start_m.setMinimumDate(QtCore.QDate(2010, 1, 1))
        self.start_m.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.start_m.setDate(QtCore.QDate(2019, 1, 1))
        self.start_m.setObjectName("start_m")
        self.gridLayout_3.addWidget(self.start_m, 1, 0, 1, 1)
        self.consult_confirmBtn = QtWidgets.QPushButton(self.Consult)
        self.consult_confirmBtn.setObjectName("consult_confirmBtn")
        self.gridLayout_3.addWidget(self.consult_confirmBtn, 4, 0, 1, 2)
        self.sourceBtn = QtWidgets.QPushButton(self.Consult)
        self.sourceBtn.setObjectName("sourceBtn")
        self.gridLayout_3.addWidget(self.sourceBtn, 8, 0, 1, 2)
        self.gridLayout_5.addWidget(self.Consult, 0, 0, 1, 1)
        self.image = QtWidgets.QLabel(self.tab_1)
        self.image.setMinimumSize(QtCore.QSize(840, 480))
        self.image.setMaximumSize(QtCore.QSize(1000, 1000))
        self.image.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.gridLayout_5.addWidget(self.image, 0, 1, 3, 1)
        self.Objection = QtWidgets.QGroupBox(self.tab_1)
        self.Objection.setObjectName("Objection")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Objection)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.excute_BTN_1 = QtWidgets.QPushButton(self.Objection)
        self.excute_BTN_1.setObjectName("excute_BTN_1")
        self.gridLayout_4.addWidget(self.excute_BTN_1, 2, 0, 1, 2)
        self.obj_folderBtn = QtWidgets.QPushButton(self.Objection)
        self.obj_folderBtn.setObjectName("obj_folderBtn")
        self.gridLayout_4.addWidget(self.obj_folderBtn, 3, 0, 1, 2)
        self.GSCM_BTN = QtWidgets.QPushButton(self.Objection)
        self.GSCM_BTN.setObjectName("GSCM_BTN")
        self.gridLayout_4.addWidget(self.GSCM_BTN, 5, 0, 1, 2)
        self.obj_fileBtn = QtWidgets.QPushButton(self.Objection)
        self.obj_fileBtn.setObjectName("obj_fileBtn")
        self.gridLayout_4.addWidget(self.obj_fileBtn, 4, 0, 1, 2)
        self.gridLayout_5.addWidget(self.Objection, 1, 0, 1, 1)
        self.DBgen = QtWidgets.QGroupBox(self.tab_1)
        self.DBgen.setObjectName("DBgen")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.DBgen)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.year_checkBX_2 = QtWidgets.QCheckBox(self.DBgen)
        self.year_checkBX_2.setObjectName("year_checkBX_2")
        self.gridLayout_2.addWidget(self.year_checkBX_2, 0, 0, 1, 1)
        self.DB_CRT_BTN = QtWidgets.QPushButton(self.DBgen)
        self.DB_CRT_BTN.setObjectName("DB_CRT_BTN")
        self.gridLayout_2.addWidget(self.DB_CRT_BTN, 2, 0, 1, 2)
        self.DB_start_m = QtWidgets.QDateEdit(self.DBgen)
        self.DB_start_m.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.DB_start_m.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DB_start_m.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.DB_start_m.setMinimumDate(QtCore.QDate(2010, 1, 1))
        self.DB_start_m.setObjectName("DB_start_m")
        self.gridLayout_2.addWidget(self.DB_start_m, 1, 0, 1, 2)
        self.DB_OPN_BTN = QtWidgets.QPushButton(self.DBgen)
        self.DB_OPN_BTN.setObjectName("DB_OPN_BTN")
        self.gridLayout_2.addWidget(self.DB_OPN_BTN, 3, 0, 1, 2)
        self.upload_BTN_2 = QtWidgets.QPushButton(self.DBgen)
        self.upload_BTN_2.setObjectName("upload_BTN_2")
        self.gridLayout_2.addWidget(self.upload_BTN_2, 4, 0, 1, 2)
        self.gridLayout_5.addWidget(self.DBgen, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.IntBR = QtWidgets.QGroupBox(self.tab_2)
        self.IntBR.setObjectName("IntBR")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.IntBR)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_exc = QtWidgets.QLineEdit(self.IntBR)
        self.lineEdit_exc.setObjectName("lineEdit_exc")
        self.gridLayout_6.addWidget(self.lineEdit_exc, 3, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.IntBR)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_6.addWidget(self.comboBox, 0, 0, 1, 3)
        self.end_m_2 = QtWidgets.QDateEdit(self.IntBR)
        self.end_m_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.end_m_2.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.end_m_2.setMinimumDate(QtCore.QDate(2010, 1, 1))
        self.end_m_2.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.end_m_2.setCurrentSectionIndex(1)
        self.end_m_2.setDate(QtCore.QDate(2020, 1, 1))
        self.end_m_2.setObjectName("end_m_2")
        self.gridLayout_6.addWidget(self.end_m_2, 1, 2, 1, 1)
        self.test_btn = QtWidgets.QPushButton(self.IntBR)
        self.test_btn.setObjectName("test_btn")
        self.gridLayout_6.addWidget(self.test_btn, 6, 0, 1, 3)
        self.br_filebtn = QtWidgets.QPushButton(self.IntBR)
        self.br_filebtn.setObjectName("br_filebtn")
        self.gridLayout_6.addWidget(self.br_filebtn, 8, 0, 1, 3)
        self.br_foldbtn = QtWidgets.QPushButton(self.IntBR)
        self.br_foldbtn.setObjectName("br_foldbtn")
        self.gridLayout_6.addWidget(self.br_foldbtn, 7, 0, 1, 3)
        self.calculate_btn = QtWidgets.QPushButton(self.IntBR)
        self.calculate_btn.setObjectName("calculate_btn")
        self.gridLayout_6.addWidget(self.calculate_btn, 5, 0, 1, 3)
        self.br_emailbtn = QtWidgets.QPushButton(self.IntBR)
        self.br_emailbtn.setObjectName("br_emailbtn")
        self.gridLayout_6.addWidget(self.br_emailbtn, 9, 0, 1, 3)
        self.lineEdit_gen = QtWidgets.QLineEdit(self.IntBR)
        self.lineEdit_gen.setObjectName("lineEdit_gen")
        self.gridLayout_6.addWidget(self.lineEdit_gen, 2, 2, 1, 1)
        self.label_gen = QtWidgets.QLabel(self.IntBR)
        self.label_gen.setObjectName("label_gen")
        self.gridLayout_6.addWidget(self.label_gen, 2, 0, 1, 1)
        self.label_exc = QtWidgets.QLabel(self.IntBR)
        self.label_exc.setObjectName("label_exc")
        self.gridLayout_6.addWidget(self.label_exc, 3, 0, 1, 1)
        self.start_m_2 = QtWidgets.QDateEdit(self.IntBR)
        self.start_m_2.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.start_m_2.setMinimumDate(QtCore.QDate(2010, 1, 1))
        self.start_m_2.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.start_m_2.setDate(QtCore.QDate(2019, 1, 1))
        self.start_m_2.setObjectName("start_m_2")
        self.gridLayout_6.addWidget(self.start_m_2, 1, 0, 1, 2)
        self.gridLayout_8.addWidget(self.IntBR, 0, 0, 1, 1)
        self.IntBR_raw = QtWidgets.QGroupBox(self.tab_2)
        self.IntBR_raw.setObjectName("IntBR_raw")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.IntBR_raw)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.comboBox_gen_exc = QtWidgets.QComboBox(self.IntBR_raw)
        self.comboBox_gen_exc.setObjectName("comboBox_gen_exc")
        self.comboBox_gen_exc.addItem("")
        self.comboBox_gen_exc.addItem("")
        self.comboBox_gen_exc.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_gen_exc, 2, 1, 1, 1)
        self.end_m_3 = QtWidgets.QDateEdit(self.IntBR_raw)
        self.end_m_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.end_m_3.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.end_m_3.setMinimumDate(QtCore.QDate(2010, 1, 1))
        self.end_m_3.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.end_m_3.setCurrentSectionIndex(1)
        self.end_m_3.setDate(QtCore.QDate(2020, 1, 1))
        self.end_m_3.setObjectName("end_m_3")
        self.gridLayout_9.addWidget(self.end_m_3, 1, 1, 1, 1)
        self.br_rawbtn = QtWidgets.QPushButton(self.IntBR_raw)
        self.br_rawbtn.setObjectName("br_rawbtn")
        self.gridLayout_9.addWidget(self.br_rawbtn, 6, 0, 1, 2)
        self.comboBox_cc = QtWidgets.QComboBox(self.IntBR_raw)
        self.comboBox_cc.setObjectName("comboBox_cc")
        self.comboBox_cc.addItem("")
        self.comboBox_cc.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_cc, 3, 1, 1, 1)
        self.br_rawfoldbtn = QtWidgets.QPushButton(self.IntBR_raw)
        self.br_rawfoldbtn.setObjectName("br_rawfoldbtn")
        self.gridLayout_9.addWidget(self.br_rawfoldbtn, 8, 0, 1, 2)
        self.start_m_3 = QtWidgets.QDateEdit(self.IntBR_raw)
        self.start_m_3.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.start_m_3.setMinimumDate(QtCore.QDate(2010, 1, 1))
        self.start_m_3.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.start_m_3.setDate(QtCore.QDate(2019, 1, 1))
        self.start_m_3.setObjectName("start_m_3")
        self.gridLayout_9.addWidget(self.start_m_3, 1, 0, 1, 1)
        self.label_exc_2 = QtWidgets.QLabel(self.IntBR_raw)
        self.label_exc_2.setObjectName("label_exc_2")
        self.gridLayout_9.addWidget(self.label_exc_2, 3, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.IntBR_raw)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_2, 0, 0, 1, 2)
        self.label_gen_3 = QtWidgets.QLabel(self.IntBR_raw)
        self.label_gen_3.setObjectName("label_gen_3")
        self.gridLayout_9.addWidget(self.label_gen_3, 4, 0, 1, 1)
        self.label_gen_exc = QtWidgets.QLabel(self.IntBR_raw)
        self.label_gen_exc.setObjectName("label_gen_exc")
        self.gridLayout_9.addWidget(self.label_gen_exc, 2, 0, 1, 1)
        self.comboBox_int_spe = QtWidgets.QComboBox(self.IntBR_raw)
        self.comboBox_int_spe.setObjectName("comboBox_int_spe")
        self.comboBox_int_spe.addItem("")
        self.comboBox_int_spe.addItem("")
        self.comboBox_int_spe.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_int_spe, 4, 1, 1, 1)
        self.gridLayout_8.addWidget(self.IntBR_raw, 1, 0, 1, 1)
        self.image_2 = QtWidgets.QLabel(self.tab_2)
        self.image_2.setMinimumSize(QtCore.QSize(840, 480))
        self.image_2.setMaximumSize(QtCore.QSize(1000, 1000))
        self.image_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.image_2.setFrameShape(QtWidgets.QFrame.Box)
        self.image_2.setText("")
        self.image_2.setScaledContents(True)
        self.image_2.setObjectName("image_2")
        self.gridLayout_8.addWidget(self.image_2, 0, 1, 2, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.mail_option = QtWidgets.QGroupBox(self.tab_3)
        self.mail_option.setObjectName("mail_option")
        self.formLayout = QtWidgets.QFormLayout(self.mail_option)
        self.formLayout.setObjectName("formLayout")
        self.label_to = QtWidgets.QLabel(self.mail_option)
        self.label_to.setObjectName("label_to")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_to)
        self.lineEdit_to = QtWidgets.QLineEdit(self.mail_option)
        self.lineEdit_to.setEnabled(False)
        self.lineEdit_to.setObjectName("lineEdit_to")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_to)
        self.label_cc = QtWidgets.QLabel(self.mail_option)
        self.label_cc.setObjectName("label_cc")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_cc)
        self.lineEdit_cc = QtWidgets.QLineEdit(self.mail_option)
        self.lineEdit_cc.setEnabled(False)
        self.lineEdit_cc.setObjectName("lineEdit_cc")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_cc)
        self.mail_disable = QtWidgets.QCheckBox(self.mail_option)
        self.mail_disable.setChecked(True)
        self.mail_disable.setObjectName("mail_disable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mail_disable)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.gridLayout_7.addWidget(self.mail_option, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        Consult2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Consult2)
        self.statusbar.setObjectName("statusbar")
        Consult2.setStatusBar(self.statusbar)
        self.setWindowIcon(QtGui.QIcon('glovis.png'))

        self.retranslateUi(Consult2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Consult2)

    def retranslateUi(self, Consult2):
        _translate = QtCore.QCoreApplication.translate
        Consult2.setWindowTitle(_translate("Consult2", "GLOVIS RECLAIM SYSTEM"))
        self.Consult.setTitle(_translate("Consult2", "품의정보"))
        self.consult_folderBtn.setText(_translate("Consult2", "생성폴더열기"))
        self.end_m.setDisplayFormat(_translate("Consult2", "yyyy-MM"))
        self.year_checkBX_1.setText(_translate("Consult2", "연도별"))
        self.email_Btn.setText(_translate("Consult2", "메일보내기"))
        self.file_Btn.setText(_translate("Consult2", "생성파일열기"))
        self.start_m.setDisplayFormat(_translate("Consult2", "yyyy-MM"))
        self.consult_confirmBtn.setText(_translate("Consult2", "생성"))
        self.sourceBtn.setText(_translate("Consult2", "소스폴더열기"))
        self.Objection.setTitle(_translate("Consult2", "이의제기"))
        self.excute_BTN_1.setText(_translate("Consult2", "실행"))
        self.obj_folderBtn.setText(_translate("Consult2", "폴더열기"))
        self.GSCM_BTN.setText(_translate("Consult2", "GSCM 열기"))
        self.obj_fileBtn.setText(_translate("Consult2", "자료열기"))
        self.DBgen.setTitle(_translate("Consult2", "DB생성"))
        self.year_checkBX_2.setText(_translate("Consult2", "연도별"))
        self.DB_CRT_BTN.setText(_translate("Consult2", "생성"))
        self.DB_start_m.setDisplayFormat(_translate("Consult2", "yyyy-MM"))
        self.DB_OPN_BTN.setText(_translate("Consult2", "DB열기"))
        self.upload_BTN_2.setText(_translate("Consult2", "업로드폴더열기"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Consult2", "General"))
        self.IntBR.setTitle(_translate("Consult2", "통합분담율"))
        self.comboBox.setItemText(0, _translate("Consult2", "HMMA"))
        self.comboBox.setItemText(1, _translate("Consult2", "KMMG"))
        self.comboBox.setItemText(2, _translate("Consult2", "KMS"))
        self.comboBox.setItemText(3, _translate("Consult2", "HMMC"))
        self.comboBox.setItemText(4, _translate("Consult2", "HMMR"))
        self.comboBox.setItemText(5, _translate("Consult2", "HMB"))
        self.comboBox.setItemText(6, _translate("Consult2", "KMM"))
        self.comboBox.setItemText(7, _translate("Consult2", "HAOS"))
        self.comboBox.setItemText(8, _translate("Consult2", "HMI"))
        self.comboBox.setItemText(9, _translate("Consult2", "KMI"))
        self.comboBox.setItemText(10, _translate("Consult2", "CHMC"))
        self.comboBox.setItemText(11, _translate("Consult2", "YOUNGSAN"))
        self.comboBox.setItemText(12, _translate("Consult2", "DWI"))
        self.end_m_2.setDisplayFormat(_translate("Consult2", "yyyy-MM"))
        self.test_btn.setText(_translate("Consult2", "테스트"))
        self.br_filebtn.setText(_translate("Consult2", "생성파일열기"))
        self.br_foldbtn.setText(_translate("Consult2", "생성폴더열기"))
        self.calculate_btn.setText(_translate("Consult2", "계산"))
        self.br_emailbtn.setText(_translate("Consult2", "메일보내기"))
        self.label_gen.setText(_translate("Consult2", "일반분담율"))
        self.label_exc.setText(_translate("Consult2", "교류분담율"))
        self.start_m_2.setDisplayFormat(_translate("Consult2", "yyyy-MM"))
        self.IntBR_raw.setTitle(_translate("Consult2", "로우데이터 생성"))
        self.comboBox_gen_exc.setItemText(0, _translate("Consult2", "전체"))
        self.comboBox_gen_exc.setItemText(1, _translate("Consult2", "일반"))
        self.comboBox_gen_exc.setItemText(2, _translate("Consult2", "교류"))
        self.end_m_3.setDisplayFormat(_translate("Consult2", "yyyy-MM"))
        self.br_rawbtn.setText(_translate("Consult2", "생성"))
        self.comboBox_cc.setItemText(0, _translate("Consult2", "전체"))
        self.comboBox_cc.setItemText(1, _translate("Consult2", "켐페인제외"))
        self.br_rawfoldbtn.setText(_translate("Consult2", "생성폴더열기"))
        self.start_m_3.setDisplayFormat(_translate("Consult2", "yyyy-MM"))
        self.label_exc_2.setText(_translate("Consult2", "캠페인"))
        self.comboBox_2.setItemText(0, _translate("Consult2", "HMMA"))
        self.comboBox_2.setItemText(1, _translate("Consult2", "KMMG"))
        self.comboBox_2.setItemText(2, _translate("Consult2", "KMS"))
        self.comboBox_2.setItemText(3, _translate("Consult2", "HMMC"))
        self.comboBox_2.setItemText(4, _translate("Consult2", "HMMR"))
        self.comboBox_2.setItemText(5, _translate("Consult2", "HMB"))
        self.comboBox_2.setItemText(6, _translate("Consult2", "KMM"))
        self.comboBox_2.setItemText(7, _translate("Consult2", "HAOS"))
        self.comboBox_2.setItemText(8, _translate("Consult2", "HMI"))
        self.comboBox_2.setItemText(9, _translate("Consult2", "KMI"))
        self.comboBox_2.setItemText(10, _translate("Consult2", "CHMC"))
        self.comboBox_2.setItemText(11, _translate("Consult2", "YOUNGSAN"))
        self.comboBox_2.setItemText(12, _translate("Consult2", "DWI"))
        self.label_gen_3.setText(_translate("Consult2", "통분/개별"))
        self.label_gen_exc.setText(_translate("Consult2", "일반/교류"))
        self.comboBox_int_spe.setItemText(0, _translate("Consult2", "전체"))
        self.comboBox_int_spe.setItemText(1, _translate("Consult2", "통분"))
        self.comboBox_int_spe.setItemText(2, _translate("Consult2", "개별"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Consult2", "Int BR"))
        self.mail_option.setTitle(_translate("Consult2", "메일 설정"))
        self.label_to.setText(_translate("Consult2", "To"))
        self.label_cc.setText(_translate("Consult2", "Cc"))
        self.mail_disable.setText(_translate("Consult2", "메일 송부 비활성화"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Consult2", "E-Mail Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Consult2 = QtWidgets.QMainWindow()
    ui = Ui_Consult2()
    ui.setupUi(Consult2)
    Consult2.show()
    sys.exit(app.exec_())
